### ISSUE TITLE
Configure log metric filters and alerts

### ISSUE THREAD

**Issue by brettcurtis** [osinfra-io/terraform-google-project#55]
Monitoring events gives insight into changes and may reduce the time it takes to detect suspicious activity.

```[tasklist]
### Tasks
- [x] Add log metric filter and alerts exist for VPC network firewall rule changes
- [x] Add log metric filter and alert exists for VPC network changes
- [x] Add log metric filter and alerts exist for custom role changes
- [x] Add log metric filter and alert exists for Cloud Storage IAM permission changes
- [x] Add log metric filter and alerts exist for VPC Network route changes
- [x] Add log metric filter and alert exists for SQL instance configuration changes
- [x] Add log metric filter and alert exists for audit configuration changes
- [x] Add log metric filter and alerts exist for project ownership assignments/changes
```

References
- https://cloud.google.com/logging/docs/logs-based-metrics
- https://cloud.google.com/monitoring/custom-metrics
- https://cloud.google.com/monitoring/alerts

**Comment by brettcurtis** [comment]
Tested all of these rules:
![image](https://github.com/osinfra-io/terraform-google-project/assets/1610100/be982147-11b1-4f2f-9ad9-5ef474c45d06)
